### ISSUE TITLE
Heroku Error: No app.json located in the repo URL provided.

### ISSUE THREAD

**Issue by sewinter** [styfle/react-server-example-tsx#158]
When I click the deploy to Heroku button in the README, Heroku displays the error in the subject line.

**Comment by styfle** [comment]
That’s strange, I don’t think this repo ever had a app.json file. Feel free to submit a PR to add one. Otherwise, you can try deploying to zeit now. Although this repo hasn’t been updated to v2 yet.

**Comment by styfle** [comment]
FYI, I just upgraded to Now 2.0 in PR #168

**Comment by styfle** [comment]
The Deploy To Now button has been updated and the Heroku button has been removed in da3b80f94b31870a0ab8ab0eda9233843e22296a

Let me know if you're still having problems 👍

**Comment by momskidvaava** [comment]
same issue on me . pls help me . 
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/momskidvaava/kaveriprobot.git)

**Comment by mHaulkhory** [comment]
The HTML code for the deploy button (first line)

<a href="https://heroku.com/deploy?template=https://github.com/YOUR_USERNAME/intro-to-heroku">
