### ISSUE TITLE
Unnessessary server webpack with @now/static-build

### ISSUE THREAD

**Issue by revskill10** [styfle/react-server-example-tsx#188]
Currently, the deployment will build static server.js, too, which is redundant.
We could check to exclude the `node` target if it's a production build ?

**Comment by styfle** [comment]
That would be nice if you could exclude it.

Ideally, there would be a separate builder such as [@now/web](https://github.com/zeit/now-builders/issues/308) and then we could remove the dependency on `webpack` completely 😄

**Comment by revskill10** [comment]
@styfle Thanks for the repo. But i found it lack of babel support. Do you have any plan to improve to support babel and code splitting ?

**Comment by styfle** [comment]
@revskill10 I think this is the same question from #189

Did you try the static builder?

**Comment by revskill10** [comment]
@styfle Yes, it works well with `@now/static-builder`.
But in this case, for example, i need to use `babel-plugin-import` on server side for React component, so only `ts-loader` is not enough.
