### ISSUE TITLE
Babel server build ?

### ISSUE THREAD

**Issue by revskill10** [styfle/react-server-example-tsx#189]
Currently, is there any way to integrate babel to `@now/node@canary` with typescript ?
For example, with `ant-design`, we need babel plugin to build (babel-plugin-import)

**Comment by styfle** [comment]
I believe you could.

I don't personally use `babel` but if you create a script and it works with `npm run now-build` then it should work with `@now/static-build`.

See the docs: https://zeit.co/docs/v2/deployments/official-builders/static-build-now-static-build/
