### ISSUE TITLE
wrong "main" at package.json

### ISSUE THREAD

**Issue by crazyx13th** [styfle/react-server-example-tsx#3]
![grafik](https://cloud.githubusercontent.com/assets/8912561/26407434/6b8de642-409b-11e7-9fc9-1d49eb3f1c21.png)

thx, nice work!

**Comment by styfle** [comment]
@crazyx13th Thanks!

Fixed in 256b3d6e381c0017c00936a210b648eca84558f1
This will be released as 3.0.1
